version: "3.7"

services:
  item-app:
    image: orochimadit/item-app:v1
    depends_on:
      - item-db
    restart: always
    ports:
      - 80:8080

  item-db:
    image: mongo:3
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - app-db:/data/db

  
volumes:
  app-db: